### ISSUE TITLE
Replace build.bff target directory with windows path variable

### ISSUE THREAD

**Issue by RobQuistNL** [kraifpatrik/yyc-overwrite#2]
```
PATH_DEFAULT = "C:\\Users\\{}\\AppData\\Local\\GameMakerStudio2\\GMS2TEMP\\build.bff".format(
        getpass.getuser())
```

I think, what you're looking for, is this simple one: `%LOCALAPPDATA%\\GameMakerStudio2\\GMS2TEMP\\build.bff`

That should always return the proper one and allows you to skip the `getuser()` call (and thus the  `getpass` library), and potentially support people that have their localappdata folder on a different disk.

**Comment by kraifpatrik** [comment]
Didn't think of that, thanks! Updated and pushed to master.
